"""Add email and password_hash to users

Revision ID: 5f7cd58ce454
Revises: 650d0277e345
Create Date: 2025-09-25 12:34:46.811605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7cd58ce454'
down_revision: Union[str, Sequence[str], None] = '650d0277e345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('roles', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roles')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
